CREATE TABLE SESSAO
(
    ID_SESSAO BIGINT auto_increment NOT NULL,
    DATA_HORA_INICIO TIMESTAMP NOT NULL,
    DATA_HORA_FIM TIMESTAMP NOT NULL,
    ID_PAUTA BIGINT NOT NULL,

    PRIMARY KEY(ID_SESSAO),

    CONSTRAINT UK_SESSAO_PAUTA UNIQUE (ID_PAUTA),
    CONSTRAINT FK_SESSAO_PAUTA FOREIGN KEY (ID_PAUTA) REFERENCES PAUTA(ID_PAUTA)

);