CREATE TABLE VOTO
(
    ID_VOTO BIGINT auto_increment NOT NULL,
    VOTO VARCHAR(3) NOT NULL,
    ID_ASSOCIADO BIGINT NOT NULL,
    ID_SESSAO BIGINT NOT NULL,

    PRIMARY KEY(ID_VOTO),

    CONSTRAINT FK_VOTO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO) REFERENCES ASSOCIADO(ID_ASSOCIADO),
    CONSTRAINT FK_VOTO_SESSAO FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(ID_SESSAO)

);